import { Profile, SuccessStory, NotificationItem, PaymentDetails } from './types';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: "mali-1",
    name: "Aarav Saini",
    gender: "Male",
    age: 28,
    dob: "1998-04-12",
    mobile: "+91 98765 43210",
    email: "aarav.saini@gmail.com",
    gotra: "Kachhawaha",
    ownGotra: "Kachhawaha",
    motherGotra: "Sankhla",
    dadiGotra: "Panwar",
    naniGotra: "Deora",
    district: "Jodhpur",
    tehsil: "Luni",
    village: "Salawas",
    education: "B.Tech in Computer Science",
    college: "IIT Bombay",
    occupation: "Senior Software Engineer",
    company: "Google India",
    income: "₹28 Lakhs / Annum",
    fatherName: "Mr. Rameshwar Saini",
    motherName: "Mrs. Kamala Devi",
    familyType: "Joint",
    brothers: "1 younger (studying)",
    sisters: "None",
    maritalStatus: "Never Married",
    preferredAge: "24 - 27",
    preferredDistrict: "Jodhpur, Jaipur, Pali",
    preferredEducation: "Graduate or above",
    preferredProfession: "IT, Banking, Teaching or Medical",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400&h=400",
    gallery: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400&h=400",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400&h=400"
    ],
    verified: true,
    premium: true,
    isShortlisted: false,
    interestStatus: "none",
    managedBy: "Self",
    isCommunityVerified: true,
    profileCompletion: 95,
    lastActive: "Active 5 mins ago",
    isOnline: true,
    familyContactTiming: "6:00 PM to 9:00 PM",
    agricultureLandDetails: "6 Bigha irrigated land near Salawas, Jodhpur",
    familyBusinessInfo: "Saini Agro Machinery & Tool Store"
  },
  {
    id: "mali-2",
    name: "Priyanka Saini",
    gender: "Female",
    age: 26,
    dob: "2000-08-19",
    mobile: "+91 87654 32109",
    email: "priyanka.saini@outlook.com",
    gotra: "Gehlot",
    ownGotra: "Gehlot",
    motherGotra: "Solanki",
    dadiGotra: "Tak",
    naniGotra: "Tanwar",
    district: "Jaipur",
    tehsil: "Sanganer",
    village: "Mohanpura",
    education: "MBBS, MD (Pediatrics)",
    college: "SMS Medical College, Jaipur",
    occupation: "Consultant Pediatrician",
    company: "Fortis Escorts Hospital",
    income: "₹18 Lakhs / Annum",
    fatherName: "Mr. Bhanwar Lal Gehlot",
    motherName: "Mrs. Prem Devi",
    familyType: "Nuclear",
    brothers: "None",
    sisters: "1 elder (married)",
    maritalStatus: "Never Married",
    preferredAge: "27 - 31",
    preferredDistrict: "Jaipur, Jodhpur, Ajmer",
    preferredEducation: "Post Graduate (MD/MS, M.Tech, MBA)",
    preferredProfession: "Doctor, Engineer, IAS/RJS Officer",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400&h=400",
    gallery: [
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400&h=400",
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400&h=400"
    ],
    verified: true,
    premium: true,
    isShortlisted: true,
    interestStatus: "received",
    managedBy: "Father",
    isCommunityVerified: true,
    profileCompletion: 100,
    lastActive: "Active now",
    isOnline: true,
    photoPrivacyMode: "Blur",
    familyContactTiming: "7:00 PM to 9:30 PM",
    agricultureLandDetails: "Shared ownership - 15 Bigha agricultural land in Mohanpura, Sanganer",
    familyBusinessInfo: "Bhanwar Saini & Sons Florist Exports"
  },
  {
    id: "mali-3",
    name: "Vikram Gehlot",
    gender: "Male",
    age: 30,
    dob: "1996-11-05",
    mobile: "+91 76543 21098",
    email: "vikram.gehlot@gmail.com",
    gotra: "Solanki",
    ownGotra: "Solanki",
    motherGotra: "Saini",
    dadiGotra: "Singhal",
    naniGotra: "Parihar",
    district: "Pali",
    tehsil: "Sumerpur",
    village: "Pomawa",
    education: "MBA (Finance)",
    college: "FMS Delhi",
    occupation: "Investment Banker",
    company: "HDFC Bank",
    income: "₹22 Lakhs / Annum",
    fatherName: "Mr. Girdhari Lal Solanki",
    motherName: "Mrs. Shanti Devi",
    familyType: "Joint",
    brothers: "2 elder (running Family Marble Business)",
    sisters: "1 younger (married)",
    maritalStatus: "Never Married",
    preferredAge: "25 - 29",
    preferredDistrict: "Pali, Jodhpur, Sirohi, Udaipur",
    preferredEducation: "Graduate / MBA / CA",
    preferredProfession: "Corporate Employee or Business",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400&h=400",
    gallery: [
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400&h=400"
    ],
    verified: true,
    premium: false,
    isShortlisted: false,
    interestStatus: "none",
    managedBy: "Brother",
    isCommunityVerified: true,
    profileCompletion: 85,
    lastActive: "Active 2 hours ago",
    isOnline: false,
    familyContactTiming: "5:00 PM to 8:30 PM",
    agricultureLandDetails: "None (Fully Urban business oriented family, owns 3 commercial retail shops in Pali)",
    familyBusinessInfo: "Gehlot Marbles & Granite Showroom, Pali"
  },
  {
    id: "mali-4",
    name: "Anjali Saini",
    gender: "Female",
    age: 25,
    dob: "2001-02-14",
    mobile: "+91 95432 10987",
    email: "anjali.saini@yahoo.com",
    gotra: "Tak",
    ownGotra: "Tak",
    motherGotra: "Gehlot",
    dadiGotra: "Borana",
    naniGotra: "Rathore",
    district: "Ajmer",
    tehsil: "Beawar",
    village: "Rupnagar",
    education: "M.Sc in Biotechnology",
    college: "MDS University, Ajmer",
    occupation: "Research Associate",
    company: "Biocon Research",
    income: "₹9 Lakhs / Annum",
    fatherName: "Mr. Kishor Kumar Tak",
    motherName: "Mrs. Rukmani Devi",
    familyType: "Nuclear",
    brothers: "1 younger (doing College)",
    sisters: "None",
    maritalStatus: "Never Married",
    preferredAge: "27 - 30",
    preferredDistrict: "Ajmer, Jaipur, Udaipur",
    preferredEducation: "B.Tech/M.Pharma/M.Sc",
    preferredProfession: "Pharma, Biotech, Tech or Government Job",
    photo: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400&h=400",
    gallery: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400&h=400"
    ],
    verified: false,
    premium: true,
    isShortlisted: false,
    interestStatus: "none",
    managedBy: "Mother",
    isCommunityVerified: false,
    profileCompletion: 78,
    lastActive: "Active 1 day ago",
    isOnline: false,
    photoPrivacyMode: "Visible",
    familyContactTiming: "6:00 PM to 9:00 PM",
    agricultureLandDetails: "8 Bighas fertile lemon orchard & agricultural land in Rupnagar, Beawar",
    familyBusinessInfo: "Kishor Flower Nursery & Wholesale Florists, Ajmer"
  },
  {
    id: "mali-5",
    name: "Rajesh Saini",
    gender: "Male",
    age: 31,
    dob: "1995-07-22",
    mobile: "+91 91234 56789",
    email: "rajesh.sa@gmail.com",
    gotra: "Tanwar",
    ownGotra: "Tanwar",
    motherGotra: "Panwar",
    dadiGotra: "Bhati",
    naniGotra: "Khichi",
    district: "Udaipur",
    tehsil: "Girwa",
    village: "Bari",
    education: "M.Tech in Structural Engineering",
    college: "MNIT Jaipur",
    occupation: "Assistant Engineer (A.En)",
    company: "Public Works Department (PWD), Rajasthan",
    income: "₹14 Lakhs / Annum",
    fatherName: "Mr. Madhav Lal Tanwar",
    motherName: "Mrs. Nirma Devi",
    familyType: "Joint",
    brothers: "1 elder (Government Teacher)",
    sisters: "2 elder (both happily married)",
    maritalStatus: "Never Married",
    preferredAge: "25 - 29",
    preferredDistrict: "Udaipur, Rajsamand, Chittorgarh",
    preferredEducation: "Graduate / B.Ed / Govt Employee preferred",
    preferredProfession: "Government Employee or Teaching Specialist",
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400&h=400",
    gallery: [
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400&h=400"
    ],
    verified: true,
    premium: false,
    isShortlisted: false,
    interestStatus: "accepted",
    managedBy: "Father",
    isCommunityVerified: true,
    profileCompletion: 90,
    lastActive: "Active 30 mins ago",
    isOnline: true
  },
  {
    id: "mali-6",
    name: "Kiran Kachhawaha",
    gender: "Female",
    age: 27,
    dob: "1999-09-30",
    mobile: "+91 93456 78901",
    email: "kiran.k@gmail.com",
    gotra: "Sankhla",
    ownGotra: "Sankhla",
    motherGotra: "Gehlot",
    dadiGotra: "Solanki",
    naniGotra: "Goyal",
    district: "Bikaner",
    tehsil: "Nokha",
    village: "Sujandesar",
    education: "Chartered Accountant (CA)",
    college: "ICAI Bikaner Chapter",
    occupation: "Senior Financial Manager",
    company: "Ernst & Young (EY)",
    income: "₹16 Lakhs / Annum",
    fatherName: "Mr. Daulat Ram Sankhla",
    motherName: "Mrs. Sita Devi",
    familyType: "Joint",
    brothers: "1 younger (assisting in family agriculture/dairy sector)",
    sisters: "1 elder (married)",
    maritalStatus: "Never Married",
    preferredAge: "28 - 32",
    preferredDistrict: "Bikaner, Jodhpur, Jaipur",
    preferredEducation: "CA, CS, MBA, B.Tech or Lawyer",
    preferredProfession: "Professional service firm, CA practice, or PSU officer",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400&h=400",
    gallery: [
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400&h=400"
    ],
    verified: true,
    premium: true,
    isShortlisted: false,
    interestStatus: "none",
    managedBy: "Self",
    isCommunityVerified: true,
    profileCompletion: 92,
    lastActive: "Active 10 mins ago",
    isOnline: true
  },
  {
    id: "mali-7",
    name: "Dr. Deepak Panwar",
    gender: "Male",
    age: 32,
    dob: "1994-03-05",
    mobile: "+91 94567 89012",
    email: "deepak.panwar@yahoo.co.in",
    gotra: "Saini",
    ownGotra: "Saini",
    motherGotra: "Panwar",
    dadiGotra: "Borana",
    naniGotra: "Tanwar",
    district: "Kota",
    tehsil: "Ladpura",
    village: "Kathera",
    education: "M.S. in Orthopedics",
    college: "SMS Medical College, Jaipur",
    occupation: "Consulting Orthopedic Surgeon",
    company: "MBS Hospital Kota & Clinic Owner",
    income: "₹35 Lakhs / Annum",
    fatherName: "Late Mr. Prabhuram Panwar",
    motherName: "Mrs. Maya Devi",
    familyType: "Nuclear",
    brothers: "None",
    sisters: "1 elder (married to a civil judge)",
    maritalStatus: "Divorced",
    divorceStatus: "Legally Divorced, No Issues/Children",
    childrenDetails: "No children",
    preferredAge: "26 - 31",
    preferredDistrict: "Kota, Jaipur, Jodhpur, Ajmer",
    preferredEducation: "BDS, MBBS, MD/MS, or Professional Corporate Degree",
    preferredProfession: "Doctor or High Profile Professional",
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400&h=400",
    gallery: [
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400&h=400"
    ],
    verified: true,
    premium: true,
    isShortlisted: false,
    interestStatus: "none",
    managedBy: "Relative",
    isCommunityVerified: true,
    profileCompletion: 100,
    lastActive: "Active 4 hours ago",
    isOnline: false
  },
  {
    id: "mali-8",
    name: "Neetu Saini",
    gender: "Female",
    age: 26,
    dob: "2000-05-18",
    mobile: "+91 95678 90123",
    email: "neetu.saini@gmail.com",
    gotra: "Deora",
    ownGotra: "Deora",
    motherGotra: "Sankhla",
    dadiGotra: "Chauhan",
    naniGotra: "Kachhawaha",
    district: "Jodhpur",
    tehsil: "Piparcity",
    village: "Sariya",
    education: "M.A. in English Literature & B.Ed",
    college: "Jai Narain Vyas University, Jodhpur",
    occupation: "Government Secondary Teacher",
    company: "Education Department, Gov of Rajasthan",
    income: "₹7.5 Lakhs / Annum",
    fatherName: "Mr. Hukamaram Deora (Retd. Superintendent)",
    motherName: "Mrs. Gayatri Devi",
    familyType: "Joint",
    brothers: "2 elder brothers (one in Police, second in Railways)",
    sisters: "1 younger (studying MCA)",
    maritalStatus: "Never Married",
    preferredAge: "28 - 32",
    preferredDistrict: "Jodhpur, Pali, Nagaur",
    preferredEducation: "Post Graduate or Government Employee preferable",
    preferredProfession: "Government Servant, Teacher, Bank PO or Engineer",
    photo: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=400&h=400",
    gallery: [
      "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=400&h=400"
    ],
    verified: true,
    premium: false,
    isShortlisted: false,
    interestStatus: "sent",
    managedBy: "Father",
    isCommunityVerified: true,
    profileCompletion: 88,
    lastActive: "Active 1 hour ago",
    isOnline: false
  }
];

export const SUCCESS_STORIES: SuccessStory[] = [
  {
    id: "story-1",
    coupleName: "Manish Saini & Kiran Gehlot",
    gotras: "Tak & Gehlot gotras union",
    location: "Jodhpur",
    weddingDate: "Nov 24, 2025",
    story: "Our families met on Rajasthan Mali Bandhan. With the detailed gotra and village configurations, both our paternal and maternal sides matched perfectly. After standard elder discussions and meeting over tea in Jodhpur, we solemnized our relationship. Truly a secure place for Mali Samaj matches!",
    photo: "https://images.unsplash.com/photo-1607190074257-dd4b7af0309f?auto=format&fit=crop&q=80&w=600&h=400"
  },
  {
    id: "story-2",
    coupleName: "Rahul Kachhawaha & Sunita Panwar",
    gotras: "Sankhla & Deora gotras union",
    location: "Jaipur",
    weddingDate: "Jan 18, 2026",
    story: "Being an IT professional based in Pune, it was hard to search for a bride who is rooted in our culture but modern in outlook. Rajasthan Mali Bandhan allowed me to filter Jaipur/Bikaner districts and find Sunita, who is a doctor. Our parents were highly satisfied with the seamless background check details.",
    photo: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80&w=600&h=400"
  },
  {
    id: "story-3",
    coupleName: "Gajendra Singhal & Pooja Saini",
    gotras: "Singhal & Saini gotras union",
    location: "Udaipur",
    weddingDate: "April 02, 2026",
    story: "A match made in heaven and discovered through state filtering. The profile creation wizard helped her father list detailed criteria. This is the first professional Mali platform that values privacy, providing transparent communication between well-respected families.",
    photo: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&q=80&w=600&h=400"
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    type: "interest",
    title: "New Interest Received",
    description: "Priyanka Saini (MD Pediatrician) has sent you a connection interest.",
    time: "2 hours ago",
    unread: true
  },
  {
    id: "notif-2",
    type: "view",
    title: "Profile Viewed",
    description: "Anjali Saini and 3 other families viewed your profile in the last 24 hours.",
    time: "1 day ago",
    unread: true
  },
  {
    id: "notif-3",
    type: "membership",
    title: "Membership Elite Activated",
    description: "Woohoo! Your premium 'Gold Plan' status is now active with unlimited views.",
    time: "2 days ago",
    unread: false
  },
  {
    id: "notif-4",
    type: "verification",
    title: "Verification Approved",
    description: "Your governmental Aadhaar Card and live selfie match 100%. Verified Badge applied!",
    time: "3 days ago",
    unread: false
  }
];

export const MOCK_PAYMENT_HISTORY: PaymentDetails[] = [
  {
    id: "pay-1",
    planName: "Gold Plan (6 Month Validity)",
    price: "₹3,100",
    date: "2026-06-11",
    paymentId: "TXN_MALI_9242940294",
    status: "Success"
  },
  {
    id: "pay-2",
    planName: "Silver Plan (3 Month Validity)",
    price: "₹1,800",
    date: "2026-03-11",
    paymentId: "TXN_MALI_1092842094",
    status: "Success"
  },
  {
    id: "pay-3",
    planName: "Gold Plan (Attempt)",
    price: "₹3,100",
    date: "2026-06-11",
    paymentId: "TXN_MALI_ERR8124924",
    status: "Failed"
  }
];

export const FAQS = [
  {
    question: "How does gotra matching work in Rajasthan Mali Bandhan?",
    answer: "In the Mali Samaj, community marriage protocols require avoiding the gotra of the father, mother, paternal grandmother, and maternal grandmother. Our registration and advanced filters allow families to clearly state these gotras, preventing overlapping matched recommendations."
  },
  {
    question: "Is this platform exclusive to the Rajasthan Mali Samaj?",
    answer: "Yes, this platform is specifically dedicated to the Rajasthan Mali Samaj, Saini, Gehlot, Kachhawaha, Solanki, and other direct sub-sects of the Mali community worldwide searching for native Rajasthan alliances."
  },
  {
    question: "How do you guarantee the verification status of brides & grooms?",
    answer: "We offer a double-factor offline and online verification process. Users can upload government-issued IDs (Aadhaar or PAN) and take a live selfie through their secure profile wizard. Verified profiles are indicated with a royal premium blue/gold shield badge."
  },
  {
    question: "Can parents handle profiles on behalf of their children?",
    answer: "Absolutely. More than 65% of the profiles on our portal are managed by parents or elder siblings. During registration, you can specify 'Profile Created By' (Self, Father, Mother, Brother, Sister, Relative)."
  },
  {
    question: "What features are unlocked in the Premium Membership?",
    answer: "Premium members can directly view verified phone numbers, chat or initiate matching requests with parents over automated SMS, seek certified Gotra check assistance, and rank higher in local search results."
  }
];
